# Generated by Django 4.2.9 on 2026-03-04 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fasiliti', models.CharField(max_length=200, verbose_name='Nama Fasiliti')),
                ('jenis_fasiliti', models.CharField(choices=[('hospital', 'Hospital'), ('hospital_pakar', 'Hospital Pakar'), ('klinik_kesihatan', 'Klinik Kesihatan'), ('klinik_desa', 'Klinik Desa'), ('klinik_komuniti', 'Klinik Komuniti'), ('lain', 'Lain-lain')], max_length=30, verbose_name='Jenis Fasiliti')),
                ('negeri', models.CharField(choices=[('johor', 'Johor'), ('kedah', 'Kedah'), ('kelantan', 'Kelantan'), ('melaka', 'Melaka'), ('negeri_sembilan', 'Negeri Sembilan'), ('pahang', 'Pahang'), ('perak', 'Perak'), ('perlis', 'Perlis'), ('pulau_pinang', 'Pulau Pinang'), ('sabah', 'Sabah'), ('sarawak', 'Sarawak'), ('selangor', 'Selangor'), ('terengganu', 'Terengganu'), ('wp_kl', 'W.P. Kuala Lumpur'), ('wp_putrajaya', 'W.P. Putrajaya'), ('wp_labuan', 'W.P. Labuan')], max_length=30, verbose_name='Negeri')),
                ('daerah', models.CharField(max_length=100, verbose_name='Daerah/Bandar')),
                ('status', models.CharField(choices=[('draf', 'Draf'), ('selesai', 'Selesai')], default='draf', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tahun_dibina', models.IntegerField(blank=True, null=True, verbose_name='Q1 – Tahun Dibina')),
                ('jenis_hospital_klinik', models.CharField(blank=True, max_length=200, verbose_name='Q2 – Jenis Hospital/Klinik')),
                ('siling_okay', models.BooleanField(blank=True, null=True, verbose_name='Q32 – Siling Okay?')),
                ('ukuran_tanah', models.TextField(blank=True, verbose_name='Q29 – Ukuran Tanah & Boleh Extend?')),
                ('kakitangan_tetap', models.IntegerField(blank=True, null=True, verbose_name='Q3 – Kakitangan Tetap')),
                ('kakitangan_kontrak', models.IntegerField(blank=True, null=True, verbose_name='Q3 – Kakitangan Kontrak')),
                ('kakitangan_mystep', models.IntegerField(blank=True, null=True, verbose_name='Q3 – Kakitangan MySTeP')),
                ('ada_kakitangan_pinjaman', models.BooleanField(blank=True, null=True, verbose_name='Q16 – Ada Staff Pinjaman?')),
                ('bilangan_shift', models.IntegerField(blank=True, null=True, verbose_name='Q21/Q39 – Bilangan Shift Sehari')),
                ('ada_ot_allowance', models.BooleanField(blank=True, null=True, verbose_name='Q38 – Ada OT/Allowance?')),
                ('bilangan_staff_non_medical', models.IntegerField(blank=True, null=True, verbose_name='Q47 – Bil. Staff Non-Medical/Admin')),
                ('waktu_beroperasi', models.CharField(blank=True, max_length=200, verbose_name='Q43 – Waktu Beroperasi')),
                ('cara_minta_cuti', models.TextField(blank=True, verbose_name='Q42 – Cara Minta Cuti & Rotasi')),
                ('isu_penempatan', models.TextField(blank=True, verbose_name='Q36 – Isu Penempatan Staff')),
                ('jenis_perkhidmatan', models.TextField(blank=True, verbose_name='Q4 – Jenis Perkhidmatan')),
                ('anggaran_pelawat_harian', models.IntegerField(blank=True, null=True, verbose_name='Q5 – Anggaran Pelawat Harian')),
                ('jenis_penyakit_kerap', models.TextField(blank=True, verbose_name='Q6 – Jenis Penyakit Kerap')),
                ('boleh_selesaikan_kes', models.BooleanField(blank=True, null=True, verbose_name='Q7 – Boleh Selesaikan Kes?')),
                ('rujukan_ke', models.CharField(blank=True, max_length=200, verbose_name='Q7 – Jika Tidak, Rujuk ke Mana?')),
                ('ada_ruang_rehat', models.BooleanField(blank=True, null=True, verbose_name='Q8 – Ada Ruang Rehat Pelawat?')),
                ('ada_hemodialisis', models.BooleanField(blank=True, null=True, verbose_name='Q9 – Ada Hemodialisis?')),
                ('unit_hemodialisis', models.IntegerField(blank=True, null=True, verbose_name='Q9 – Bilangan Unit Hemodialisis')),
                ('bekalan_ubat_mencukupi', models.BooleanField(blank=True, null=True, verbose_name='Q10/Q20 – Bekalan Ubat/Perubatan Mencukupi?')),
                ('keperluan_oksigen', models.TextField(blank=True, verbose_name='Q27 – Keperluan Oksigen')),
                ('ada_emr', models.BooleanField(blank=True, null=True, verbose_name='Q30 – Ada EMR (Sistem Pendigitalan)?')),
                ('wad_diasingkan', models.BooleanField(blank=True, null=True, verbose_name='Q34 – Wad Diasingkan (L/P)?')),
                ('kualiti_makanan', models.TextField(blank=True, verbose_name='Q35 – Kualiti Makanan')),
                ('siapa_manage', models.CharField(blank=True, max_length=200, verbose_name='Q37 – Siapa In-Charge Fasiliti?')),
                ('masa_tunggu', models.CharField(blank=True, max_length=100, verbose_name='Q46 – Masa Tunggu Rawatan')),
                ('ada_osca', models.BooleanField(blank=True, null=True, verbose_name='Q48 – Ada OSCA (Kes Dadah)?')),
                ('disposable_mencukupi', models.BooleanField(blank=True, null=True, verbose_name='Q11 – Disposable Assets Mencukupi?')),
                ('keadaan_aset', models.TextField(blank=True, verbose_name='Q12 – Keadaan Aset (Umur & Fungsi)')),
                ('keadaan_ambulans', models.TextField(blank=True, verbose_name='Q15 – Keadaan Ambulans')),
                ('ada_ambulans', models.BooleanField(blank=True, null=True, verbose_name='Q15 – Ada Ambulans?')),
                ('aset_perlu_diganti', models.TextField(blank=True, verbose_name='Q24 – Aset Yang Perlu Diganti')),
                ('aset_tidak_ikut_spec', models.TextField(blank=True, verbose_name='Q25 – Aset Tidak Ikut Spec KKM')),
                ('umur_komputer', models.TextField(blank=True, verbose_name='Q31 – Umur Komputer')),
                ('keadaan_perabot', models.TextField(blank=True, verbose_name='Q13 – Keadaan Perabot/Infrastruktur')),
                ('ada_quarters', models.BooleanField(blank=True, null=True, verbose_name='Q14 – Ada Quarters?')),
                ('quarters_mencukupi', models.BooleanField(blank=True, null=True, verbose_name='Q14 – Quarters Mencukupi?')),
                ('ada_isu_parking', models.BooleanField(blank=True, null=True, verbose_name='Q22/Q40 – Ada Isu Parking?')),
                ('masalah_aircond', models.BooleanField(blank=True, null=True, verbose_name='Q23/Q41 – Ada Masalah Aircond/Kipas?')),
                ('ruang_kerja_mencukupi', models.BooleanField(blank=True, null=True, verbose_name='Q26 – Ruang Kerja/Treatment Mencukupi?')),
                ('ada_bilik_mayat', models.BooleanField(blank=True, null=True, verbose_name='Q33 – Ada Bilik Mayat?')),
                ('ada_pantry', models.BooleanField(blank=True, null=True, verbose_name='Q29b – Ada Kawasan Rehat Staff?')),
                ('ada_kantin', models.BooleanField(blank=True, null=True, verbose_name='Q44 – Ada Kantin/Mini Mart?')),
                ('ada_security', models.BooleanField(blank=True, null=True, verbose_name='Q45 – Ada Security?')),
                ('perkhidmatan_baru', models.TextField(blank=True, verbose_name='Q18 – Perkhidmatan Baru Yang Ingin Diwujudkan')),
                ('fasiliti_diperlukan', models.TextField(blank=True, verbose_name='Q19 – Fasiliti Yang Sangat Diperlukan')),
                ('maintenance_okay', models.BooleanField(blank=True, null=True, verbose_name='Q28 – Maintenance Konsesi OK?')),
                ('masalah_utama', models.TextField(blank=True, verbose_name='Q17 – Masalah Utama')),
                ('wishlist', models.TextField(blank=True, verbose_name='Q17a – Wishlist')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Fasiliti',
                'verbose_name_plural': 'Profil Fasiliti',
                'ordering': ['-created_at'],
            },
        ),
    ]
