# Generated by Django 4.2.9 on 2026-03-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_kluster_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maklumatasas',
            options={'verbose_name': 'K0 – Maklumat Asas', 'verbose_name_plural': 'K0 – Maklumat Asas'},
        ),
        migrations.AlterField(
            model_name='facilityprofile',
            name='maklumat_asas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='home.maklumatasas', verbose_name='K0 – Maklumat Asas'),
        ),
        migrations.AlterField(
            model_name='klusteraset',
            name='aset_perlu_diganti',
            field=models.TextField(blank=True, verbose_name='Q24 – Aset Yang Perlu Diganti'),
        ),
        migrations.AlterField(
            model_name='klusteraset',
            name='disposable_mencukupi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q11 – Disposable Assets Mencukupi?'),
        ),
        migrations.AlterField(
            model_name='klusteraset',
            name='keadaan_aset',
            field=models.TextField(blank=True, verbose_name='Q12 – Keadaan Aset (Umur & Fungsi)'),
        ),
        migrations.AlterField(
            model_name='klusterfasiliti',
            name='ada_kantin',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q44 – Ada Kantin/Mini Mart?'),
        ),
        migrations.AlterField(
            model_name='klusterfasiliti',
            name='ada_pantry',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q29b – Ada Kawasan Rehat Staff?'),
        ),
        migrations.AlterField(
            model_name='klusterfasiliti',
            name='masalah_aircond',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q23/Q41 – Ada Masalah Aircond?'),
        ),
        migrations.AlterField(
            model_name='klusterperancangan',
            name='fasiliti_diperlukan',
            field=models.TextField(blank=True, verbose_name='Q19 – Fasiliti Yang Sangat Diperlukan'),
        ),
        migrations.AlterField(
            model_name='klusterperancangan',
            name='perkhidmatan_baru',
            field=models.TextField(blank=True, verbose_name='Q18 – Perkhidmatan Baru Yang Ingin Diwujudkan'),
        ),
        migrations.AlterField(
            model_name='klusterperkhidmatan',
            name='ada_ruang_rehat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q8 – Ada Ruang Rehat Pelawat?'),
        ),
        migrations.AlterField(
            model_name='klusterperkhidmatan',
            name='masa_tunggu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Q46 – Masa Tunggu Rawatan'),
        ),
        migrations.AlterField(
            model_name='klusterperkhidmatan',
            name='rujukan_ke',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q7 – Jika Tidak, Rujuk ke Mana?'),
        ),
        migrations.AlterField(
            model_name='klusterperkhidmatan',
            name='unit_hemodialisis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Q9 – Bilangan Unit Hemodialisis'),
        ),
        migrations.AlterField(
            model_name='klusterperkhidmatan',
            name='wad_diasingkan',
            field=models.BooleanField(blank=True, null=True, verbose_name='Q34 – Wad Diasingkan (L/P)?'),
        ),
        migrations.AlterField(
            model_name='maklumatasas',
            name='jenis_fasiliti',
            field=models.CharField(choices=[('institusi_perubatan_khas', 'Institusi Perubatan Khas'), ('institusi_latihan', 'Institusi Latihan'), ('jabatan_kes_negeri', 'Jabatan Kesihatan Negeri'), ('klinik_pergigian_hosp', 'Klinik Pergigian di Hospital'), ('kk_ibu_anak', 'Klinik Kesihatan Ibu dan Anak'), ('klinik_pergigian_utc', 'Klinik Pergigian UTC'), ('klinik_pergigian_sekolah', 'Klinik Pergigian di Sekolah'), ('kp_kk_utc', 'Klinik Pergigian di Klinik Kesihatan UTC'), ('kp_kk_ibu_anak', 'Klinik Pergigian di Klinik Kesihatan Ibu dan Anak'), ('klinik_pergigian_rtc', 'Klinik Pergigian RTC'), ('klinik_kesihatan_utc', 'Klinik Kesihatan UTC'), ('klinik_pergigian', 'Klinik Pergigian'), ('pkp_bahagian', 'Pejabat Kesihatan Pergigian Bahagian'), ('pkp', 'Pejabat Kesihatan Pergigian'), ('pkp_daerah', 'Pejabat Kesihatan Pergigian Daerah'), ('pkp_kawasan', 'Pejabat Kesihatan Pergigian Kawasan')], max_length=30, verbose_name='Jenis Fasiliti'),
        ),
    ]
