# Generated by Django 4.2.9 on 2026-03-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_facility_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maklumatasas',
            name='jenis_fasiliti',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('hospital_pakar', 'Hospital Pakar'), ('klinik_kesihatan', 'Klinik Kesihatan'), ('klinik_desa', 'Klinik Desa'), ('klinik_komuniti', 'Klinik Komuniti'), ('institusi_perubatan_khas', 'Institusi Perubatan Khas'), ('institusi_latihan', 'Institusi Latihan'), ('jabatan_kes_negeri', 'Jabatan Kesihatan Negeri'), ('klinik_pergigian_hosp', 'Klinik Pergigian di Hospital'), ('kk_ibu_anak', 'Klinik Kesihatan Ibu dan Anak'), ('klinik_pergigian_utc', 'Klinik Pergigian UTC'), ('klinik_pergigian_sekolah', 'Klinik Pergigian di Sekolah'), ('kp_kk_utc', 'Klinik Pergigian di Klinik Kesihatan UTC'), ('kp_kk_ibu_anak', 'Klinik Pergigian di Klinik Kesihatan Ibu dan Anak'), ('klinik_pergigian_rtc', 'Klinik Pergigian RTC'), ('klinik_kesihatan_utc', 'Klinik Kesihatan UTC'), ('klinik_pergigian', 'Klinik Pergigian'), ('pkp_bahagian', 'Pejabat Kesihatan Pergigian Bahagian'), ('pkp', 'Pejabat Kesihatan Pergigian'), ('pkp_daerah', 'Pejabat Kesihatan Pergigian Daerah'), ('pkp_kawasan', 'Pejabat Kesihatan Pergigian Kawasan'), ('lain', 'Lain-lain')], max_length=30, verbose_name='Jenis Fasiliti'),
        ),
    ]
