# Generated by Django 4.2.9 on 2026-03-05 00:15

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_original_facility_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityprofile',
            name='tahun',
            field=models.IntegerField(default=home.models._current_year, verbose_name='Tahun'),
        ),
    ]
