# Generated by Django 4.2.9 on 2026-03-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_tahun_to_facilityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_top_management',
            field=models.BooleanField(default=False, verbose_name='Top Management'),
        ),
    ]
