# Generated by Django 4.2.9 on 2026-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_top_management_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_jkn',
            field=models.BooleanField(default=False, verbose_name='JKN - Hospital & Klinik'),
        ),
    ]
