# Generated by Django 4.2.9 on 2026-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_add_jkn_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_facility_names',
            field=models.JSONField(blank=True, default=list, verbose_name='Fasiliti Diperuntukkan'),
        ),
    ]
