# Generated by Django 4.2.9 on 2026-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_add_assigned_facility_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusterperkhidmatan',
            name='bilangan_osca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Q48a – Bilangan OSCA'),
        ),
    ]
