# Generated by Django 4.2.9 on 2026-03-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_klusterperkhidmatan_bilangan_osca'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklumatasas',
            name='alamat',
            field=models.TextField(blank=True, verbose_name='Alamat'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='poskod',
            field=models.CharField(blank=True, max_length=10, verbose_name='Poskod'),
        ),
        migrations.AlterField(
            model_name='maklumatasas',
            name='daerah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Daerah/Bandar'),
        ),
        migrations.AlterField(
            model_name='maklumatasas',
            name='negeri',
            field=models.CharField(blank=True, choices=[('johor', 'Johor'), ('kedah', 'Kedah'), ('kelantan', 'Kelantan'), ('melaka', 'Melaka'), ('negeri_sembilan', 'Negeri Sembilan'), ('pahang', 'Pahang'), ('perak', 'Perak'), ('perlis', 'Perlis'), ('pulau_pinang', 'Pulau Pinang'), ('sabah', 'Sabah'), ('sarawak', 'Sarawak'), ('selangor', 'Selangor'), ('terengganu', 'Terengganu'), ('wp_kl', 'W.P. Kuala Lumpur'), ('wp_putrajaya', 'W.P. Putrajaya'), ('wp_labuan', 'W.P. Labuan')], max_length=30, verbose_name='Negeri'),
        ),
    ]
