# Generated by Django 4.2.9 on 2026-03-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_add_alamat_poskod_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklumatasas',
            name='kod_fasiliti',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kod Fasiliti'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='parlimen',
            field=models.CharField(blank=True, max_length=150, verbose_name='Parlimen'),
        ),
    ]
