# Generated by Django 4.2.9 on 2026-03-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_move_kod_parlimen_to_k1'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklumatasas',
            name='parlimen',
            field=models.CharField(blank=True, max_length=150, verbose_name='Parlimen'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='wilayah',
            field=models.CharField(blank=True, choices=[('utara', 'Utara (Perlis, Kedah, P.Pinang, Perak)'), ('tengah', 'Tengah (Selangor, KL, Putrajaya, N.Sembilan, Melaka)'), ('selatan', 'Selatan (Johor)'), ('timur', 'Timur (Pahang, Kelantan, Terengganu)'), ('sabah', 'Sabah'), ('sarawak', 'Sarawak'), ('labuan', 'W.P. Labuan')], max_length=20, verbose_name='Wilayah'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='zon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zon'),
        ),
    ]
