# Generated by Django 4.2.9 on 2026-03-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_add_wilayah_zon_parlimen_to_maklumat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityprofile',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tutup', 'Tutup')], default='aktif', max_length=10),
        ),
    ]
