# Generated by Django 6.1 on 2026-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_status_aktif_tutup'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityprofile',
            name='catatan_lawatan',
            field=models.TextField(blank=True, verbose_name='Catatan/Tindakan'),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='nama_program_lawatan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Program/VIP'),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='status_lawatan',
            field=models.CharField(choices=[('merah', 'Belum Dilawati'), ('kuning', 'Dalam Perancangan/Proses'), ('biru', 'Sudah Dilawati'), ('hijau', 'Selesai/Dilaksanakan')], default='merah', max_length=10, verbose_name='Status Lawatan'),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='tarikh_lawatan',
            field=models.DateField(blank=True, null=True, verbose_name='Tarikh Lawatan'),
        ),
    ]
