# Generated by Django 6.1 on 2026-09-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_facilityprofile_catatan_lawatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklumatasas',
            name='emel_responden',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Emel Responden'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='jawatan_responden',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jawatan Responden'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='nama_responden',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Penuh Responden'),
        ),
        migrations.AddField(
            model_name='maklumatasas',
            name='no_telefon_responden',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telefon Responden'),
        ),
    ]
