# Generated by Django 6.1 on 2026-09-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_maklumatasas_emel_responden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusterfasiliti',
            name='ada_parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ada Parking Disediakan?'),
        ),
        migrations.AddField(
            model_name='klusterfasiliti',
            name='aircond_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Aircond'),
        ),
        migrations.AddField(
            model_name='klusterfasiliti',
            name='kipas_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Kipas'),
        ),
        migrations.AddField(
            model_name='klusterfasiliti',
            name='masalah_kipas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Masalah Kipas?'),
        ),
        migrations.AddField(
            model_name='klusterfasiliti',
            name='parking_mencukupi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parking Mencukupi?'),
        ),
        migrations.AddField(
            model_name='klusterkejuruteraan',
            name='siling_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Siling'),
        ),
        migrations.AddField(
            model_name='klusterkejuruteraan',
            name='tanah_mencukupi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tanah Mencukupi?'),
        ),
    ]
