# Generated by Django 6.1 on 2026-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_klusterfasiliti_ada_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusteraset',
            name='ambulans_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Ambulans'),
        ),
        migrations.AddField(
            model_name='klusteraset',
            name='gajet_ict_baik',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gajet ICT Baik?'),
        ),
        migrations.AddField(
            model_name='klusteraset',
            name='gajet_ict_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Gajet ICT'),
        ),
        migrations.AddField(
            model_name='klusteraset',
            name='senarai_peralatan',
            field=models.TextField(blank=True, verbose_name='Senarai Peralatan Perubatan'),
        ),
        migrations.AddField(
            model_name='klusteraset',
            name='sistem_pendigitalan',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sistem Pendigitalan'),
        ),
    ]
