# Generated by Django 6.1 on 2026-09-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_klusteraset_ambulans_nota_klusteraset_gajet_ict_baik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='ada_fasiliti_petugas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ada Fasiliti/Layanan Petugas?'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='ada_isu_kakitangan',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ada Isu/Krisis Kakitangan?'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='corak_penugasan',
            field=models.TextField(blank=True, verbose_name='Corak Penugasan'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='jenis_shift',
            field=models.TextField(blank=True, verbose_name='Bilangan Shift (Teks)'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='jumlah_kekosongan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Kekosongan'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='jumlah_pengisian',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pengisian'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='jumlah_perjawatan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Perjawatan'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='nota_kakitangan_pinjaman',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Pinjaman Staf'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='pengurusan_jadual',
            field=models.TextField(blank=True, verbose_name='Pengurusan Jadual (Roster)'),
        ),
        migrations.AddField(
            model_name='klustersumbermanusia',
            name='status_pertukaran_staf',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status Pertukaran Staf'),
        ),
    ]
