# Generated by Django 6.1 on 2026-09-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_klustersumbermanusia_ada_fasiliti_petugas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusterperkhidmatan',
            name='kekangan_rawatan',
            field=models.TextField(blank=True, verbose_name='Kekangan Rawatan (Jika Tidak Boleh Selesai Kes)'),
        ),
        migrations.AddField(
            model_name='klusterperkhidmatan',
            name='ruang_tunggu_nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota Ruang Menunggu'),
        ),
        migrations.AddField(
            model_name='klusterperkhidmatan',
            name='ruang_tunggu_selesa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ruang Menunggu Selesa?'),
        ),
    ]
