# Generated by Django 6.1 on 2026-09-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_klusterperkhidmatan_kekangan_rawatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusterperancangan',
            name='belanja_mengurus',
            field=models.CharField(blank=True, max_length=255, verbose_name='Belanja Mengurus (OE)'),
        ),
        migrations.AddField(
            model_name='klusterperancangan',
            name='belanja_pembangunan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Belanja Pembangunan (DE)'),
        ),
    ]
