# Generated by Django 6.1 on 2026-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_klusterperancangan_belanja_mengurus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klusterkonsesi',
            name='hemodialisis_nota',
            field=models.TextField(blank=True, verbose_name='Nota Mesin Hemodialisis'),
        ),
        migrations.AddField(
            model_name='klusterkonsesi',
            name='prosedur_kes_dadah',
            field=models.TextField(blank=True, verbose_name='Prosedur Kes Dadah'),
        ),
        migrations.AddField(
            model_name='klusterkonsesi',
            name='status_bekalan_oksigen',
            field=models.CharField(blank=True, max_length=150, verbose_name='Status Bekalan Oksigen'),
        ),
        migrations.AddField(
            model_name='klusterkonsesi',
            name='wishlist_fail',
            field=models.FileField(blank=True, null=True, upload_to='wishlist_files/', verbose_name='Fail Wishlist'),
        ),
    ]
