# Generated by Django 6.1 on 2026-10-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_klusterkonsesi_hemodialisis_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StafFasiliti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_staf', models.CharField(max_length=200, verbose_name='Nama Penuh Staf')),
                ('no_pengenalan', models.CharField(blank=True, max_length=50, verbose_name='No. Kad Pengenalan / Pekerja')),
                ('skim', models.CharField(choices=[('pakar', 'Kumpulan Pakar (FMS/Pakar Perubatan/Pakar Pergigian)'), ('perubatan', 'Kumpulan Perubatan & Pergigian (MO/Pegawai Pergigian)'), ('paramedik', 'Kumpulan Paramedik & Kejururawatan (PPP/Jururawat/JM/Juruterapi)'), ('farmasi', 'Kumpulan Farmasi (Pegawai Farmasi/PPF)'), ('allied_health', 'Kumpulan Sains Kesihatan Bersekutu (JTMP/Juru X-Ray/Dietetik/dll)'), ('sokongan', 'Kumpulan Pentadbiran, Logistik & Sokongan (PT/PPK/Pemandu/Awam)')], max_length=50, verbose_name='Kategori Skim Perkhidmatan')),
                ('gred', models.CharField(blank=True, max_length=20, verbose_name='Gred (Cth: UD41, U29, N19)')),
                ('status_lantikan', models.CharField(choices=[('tetap', 'Tetap'), ('kontrak', 'Kontrak'), ('mystep', 'MySTEP'), ('pinjaman_in', 'Pinjaman Masuk (Dari Fasiliti Lain)'), ('pinjaman_out', 'Pinjaman Keluar (Berkhidmat di tempat lain)')], max_length=30, verbose_name='Status Lantikan')),
                ('tarikh_tamat_perkhidmatan', models.DateField(blank=True, null=True, verbose_name='Tarikh Tamat Kontrak/MySTEP/Pinjaman')),
                ('catatan_mobilisasi', models.CharField(blank=True, max_length=250, verbose_name='Catatan (Lokasi Pinjaman dsb.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kluster_sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senarai_staf', to='home.klustersumbermanusia')),
            ],
            options={
                'verbose_name': 'Staf Fasiliti',
                'verbose_name_plural': 'Senarai Staf Fasiliti',
                'ordering': ['skim', 'nama_staf'],
            },
        ),
    ]
