# Generated by Django 6.1 on 2026-10-05 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_staffasiliti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalanTambahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(choices=[('latar_belakang', 'Bahagian 1: Latar Belakang'), ('infrastruktur', 'Bahagian 2: Infrastruktur Fasiliti'), ('aset', 'Bahagian 3: Aset Perubatan'), ('sumber_manusia', 'Bahagian 4: Pengurusan Sumber Manusia'), ('perkhidmatan', 'Bahagian 5: Penyampaian Perkhidmatan'), ('kewangan', 'Bahagian 6: Kewangan & Perancangan'), ('lain_lain', 'Bahagian 7: Lain-lain')], max_length=50, verbose_name='Modul / Bahagian')),
                ('teks_soalan', models.CharField(max_length=300, verbose_name='Teks Soalan')),
                ('jenis_input', models.CharField(choices=[('teks', 'Teks Ringkas'), ('textarea', 'Teks Panjang / Huraian'), ('nombor', 'Nombor'), ('ya_tidak', 'Pilihan Ya / Tidak'), ('dropdown', 'Pilihan Dropdown (Asingkan pilihan dengan koma)'), ('fail', 'Muat Naik Fail / Dokumen')], default='teks', max_length=20, verbose_name='Jenis Input')),
                ('pilihan_dropdown', models.TextField(blank=True, verbose_name='Pilihan Dropdown (Asingkan dengan koma: Pilihan A, Pilihan B)')),
                ('is_wajib', models.BooleanField(default=False, verbose_name='Wajib Diisi?')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Soalan Aktif?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soalan Tambahan Dinamik',
                'verbose_name_plural': 'Soalan Tambahan Dinamik',
            },
        ),
        migrations.CreateModel(
            name='JawapanSoalanTambahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawapan_teks', models.TextField(blank=True, verbose_name='Jawapan Teks / Pilihan')),
                ('jawapan_fail', models.FileField(blank=True, null=True, upload_to='jawapan_tambahan_files/', verbose_name='Fail Lampiran')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil_fasiliti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawapan_tambahan', to='home.facilityprofile')),
                ('soalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawapan_set', to='home.soalantambahan')),
            ],
            options={
                'verbose_name': 'Jawapan Soalan Tambahan',
                'verbose_name_plural': 'Jawapan Soalan Tambahan',
                'unique_together': {('profil_fasiliti', 'soalan')},
            },
        ),
    ]
